### ISSUE TITLE
Can response be nil in HandleIf function?

### ISSUE THREAD

**Issue by sonu27** [failsafe-go/failsafe-go#58]
I've gotten cases where response is nil and have had to handle it like so:

```go
retryPolicy: retrypolicy.Builder[*http.Response]().
			HandleIf(func(resp *http.Response, _ error) bool {
				if resp == nil {
					return false
				}
				return resp.StatusCode >= 500
			}).
...
```

Stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102f59d10]

goroutine 18 [running]:
testing.tRunner.func1.2({0x1030564c0, 0x1032fa390})
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1634 +0x33c
panic({0x1030564c0?, 0x1032fa390?})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:770 +0x124
alfred/pkg/mulesoft.NewClient.func1(0x10303a260?, {0x1030b3088?, 0x58?})
	/Users/arai/Companies/belron/go-alfred/pkg/mulesoft/client.go:72
github.com/failsafe-go/failsafe-go/internal/util.AppliesToAny[...](...)
	/Users/arai/go/pkg/mod/github.com/failsafe-go/failsafe-go@v0.6.5-0.20240708034423-87c824e3dc5d/internal/util/util.go:38
github.com/failsafe-go/failsafe-go/policy.(*BaseFailurePolicy[...]).IsFailure(0x0, 0x0?, {0x1030d6780, 0x140001a2d80})
	/Users/arai/go/pkg/mod/github.com/failsafe-go/failsafe-go@v0.6.5-0.20240708034423-87c824e3dc5d/policy/policy.go:55 +0xa8
github.com/failsafe-go/failsafe-go/policy.(*BaseExecutor[...]).IsFailure(...)
	/Users/arai/go/pkg/mod/github.com/failsafe-go/failsafe-go@v0.6.5-0.20240708034423-87c824e3dc5d/policy/policyexecutor.go:73
github.com/failsafe-go/failsafe-go/policy.(*BaseExecutor[...]).PostExecute(0x1030ddae0, {0x1037e80b0, 0x14000226000}, 0x1400007ada0)
	/Users/arai/go/pkg/mod/github.com/failsafe-go/failsafe-go@v0.6.5-0.20240708034423-87c824e3dc5d/policy/policyexecutor.go:62 +0x58
github.com/failsafe-go/failsafe-go/retrypolicy.(*retryPolicyExecutor[...]).Apply.func1()
	/Users/arai/go/pkg/mod/github.com/failsafe-go/failsafe-go@v0.6.5-0.20240708034423-87c824e3dc5d/retrypolicy/retryexecutor.go:40 +0xb0
github.com/failsafe-go/failsafe-go.(*executor[...]).execute(0x1030df560, 0x14000200090, 0x14000226000, 0x0)
	/Users/arai/go/pkg/mod/github.com/failsafe-go/failsafe-go@v0.6.5-0.20240708034423-87c824e3dc5d/executor.go:272 +0x124
github.com/failsafe-go/failsafe-go.(*executor[...]).executeSync(0x1030df560, 0x14000200090, 0x0)
	/Users/arai/go/pkg/mod/github.com/failsafe-go/failsafe-go@v0.6.5-0.20240708034423-87c824e3dc5d/executor.go:224 +0x60
github.com/failsafe-go/failsafe-go.(*executor[...]).Get(0x1030df560, 0x14000200078)
	/Users/arai/go/pkg/mod/github.com/failsafe-go/failsafe-go@v0.6.5-0.20240708034423-87c824e3dc5d/executor.go:183 +0x84
```

What are the cases when it can be nil?
Might be worth updating docs with the handling of this, as it will panic when this happens.

Update: Just noticed this happens when the http timeout on the client is exceeded.

**Comment by jhalterman** [comment]
> What are the cases when it can be nil?

The same as they would be for any http.Client request. If the client returns a nil response and an error, then that's what the RetryPolicy will receive.

> Might be worth updating docs with the handling of this

Sure - where do you think would be a good place? On the website docs or in the RetryPolicy godocs?

**Comment by sonu27** [comment]
So any examples showing HandleIf() being used with http.Response, such as:
- https://github.com/failsafe-go/failsafe-go/blob/main/examples/http_test.go#L74
- https://github.com/failsafe-go/failsafe-go/blob/main/examples/http_test.go#L100
- docs website: https://github.com/search?q=repo%3Afailsafe-go%2Ffailsafe-go.dev%20handleif&type=code

The should be updated with or similar:
```go
if resp == nil {
	return false
}
```

What do you think?

**Comment by jhalterman** [comment]
Thanks for pointing this out. Updated in a0ac62d and the website docs in https://github.com/failsafe-go/failsafe-go.dev/commit/17a295d546a390a8063b46034b59dce868b22fbd.

**Comment by sonu27** [comment]
Perfect :)
